name: CI-Dev

on: [push]

jobs:
  install-dev:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    name: "Verify dev env"
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: '3.10'
      - name: "Install in dev mode"
        run: |
          python -m pip install -U pip wheel setuptools 
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -r docs/requirements.txt
          python -m pip install -e .
          python -c 'import scml; print(scml.__version__)'          
          yes | python -m pip uninstall negmas
          python -m pip install git+https://github.com/yasserfarouk/negmas.git
          python -c 'import scml; print(scml.__version__)'
